name: fs-web
recipe: drupal10
config:
  webroot: web
  php: "8.1"
  via: nginx
  build:
    - composer install
services:
  appserver:
    webroot: web  
    xdebug: 'develop,debug'
  # For frontend building only.
  node:
    type: node:18
tooling:
  drush:
    env:
      DRUSH_OPTIONS_URI: "https://fs-web.lndo.site:4434"
  scratch:
    service: appserver
    description: Build the site from fixed data.
    cmd:
      - composer install
      - drush site:install minimal --yes
      - drush config:set system.site uuid '67893125-a67c-49fe-ab82-c1e0fd0dc8f9' --yes
      - drush config:import --yes
      - drush pm:install fs_test default_content --yes
  frontend:
    service: node
    description: Build the frontend vite
    cmd:
      - npm --prefix web/themes/custom/fstheme ci
      - npm --prefix web/themes/custom/fstheme run build
