name: "hello world"

on:
  push:
    branches:
      - nonexistent-branch-this-workflow-is-disabled  # do not change without review
  pull_request:
    branches:
      - nonexistent-branch-this-workflow-is-disabled  # do not change without review
jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v6

      - name: Test
        run: |
          echo "Ref:    ${{ env.FORGEJO_SHA }}"
          echo "Commit: ${{ env.FORGEJO_REF_NAME }}"
