#!/bin/bash

ddev drush dcer media --folder=modules/custom/fs_content/content
ddev drush dcer node --folder=modules/custom/fs_content/content
ddev drush dcer block_content --folder=modules/custom/fs_content/content
