#!/bin/bash

# Install the site directly from the config.
# ddev drush si minimal --existing-config --yes

if [ ! -f _db_main.sqlite ]; then
  echo "Missing _db_main.sqlite."
  exit 1
fi

ddev drush cr

ddev drush config:status

ddev drush updb -y

ddev drush uli
