#!/bin/bash

## Description: Installs Starshot and opens it in a browser.

ddev delete -O -y
rm web/sites/default/settings.php
rm -rf web/sites/default/files
rm -rf vendor composer.lock
ddev start
ddev composer install
cd web && php -d memory_limit=512M core/scripts/drupal install ../recipes/ce
ddev drush uli
