#!/bin/bash

# Any site building changes should be captured.
ddev drush cex -y

# Trim unneeded table data.
echo "Removing cache data."
ddev drush sqlq " \
  DELETE FROM cache_access_policy; \
  DELETE FROM cache_bootstrap; \
  DELETE FROM cache_config; \
  DELETE FROM cache_container; \
  DELETE FROM cache_data; \
  DELETE FROM cache_default; \
  DELETE FROM cache_discovery; \
  DELETE FROM cache_dynamic_page_cache; \
  DELETE FROM cache_tome_static; \
  DELETE FROM cache_toolbar; \
  DELETE FROM queue; \
  DELETE FROM router; \
  DELETE FROM sessions; \
"

# The SQLite database is already stored on disk at _db_main.sqlite.

# So we can keep working.
ddev drush cr
ddev drush uli
