<?php

/**
 * @file
 * FS Test module install hooks.
 */

/**
 * Implements hook_requirements().
 */
function fs_test_requirements(string $phase): array {
  $requirements = [];
  if ($phase === 'install') {
    $error = t('FS Test module can not be installed on production and config is excluded in "config_exclude_modules" setting in settings.php');

    if (getenv('PLATFORM_ENVIRONMENT_TYPE') === 'production') {
      if (php_sapi_name() == 'cli') {
        // Prevent user from bypassing with Drush.
        throw new \Exception($error);
      }

      $requirements['fs_test_no_production'] = [
        'severity' => REQUIREMENT_ERROR,
        'description' => $error,
      ];
    }
  }

  return $requirements;
}
