name: 'CE Base'
description: 'A CE Recipe Base.'
type: 'Site'
install:
  - admin_toolbar
  - admin_toolbar_tools
  - admin_toolbar_search
  - field_group
  - linkit
  - config
  - node
  - user
  - text
  - link
  - filter
  - block
  - block_content
  - ckeditor5
  - contextual
  - menu_link_content
  - datetime
  - block_content
  - editor
  - image
  - menu_ui
  - options
  - path
  - dynamic_page_cache
  - big_pipe
  - taxonomy
  - dblog
  - toolbar
  - field_ui
  - media
  - media_library
  - views
  - views_ui
  - fstheme
  - gin
  - gin_login
  - gin_toolbar
  - config_ignore
  - pathauto
  - redirect
config:
  actions:
    node.settings:
      simple_config_update:
        use_admin_theme: true
    system.theme:
      simple_config_update:
        admin: 'gin'
        default: 'fstheme'
