#!/bin/bash

rm -rf /var/www/html/static-site

GENERATE_STATIC_SITE=1 drush tome:static --uri=https://frees.au

# Need this one to make search api lunr works.
# Make sure Drupal site is fully index first.
cp -R "/var/www/html/web/sites/default/files/search-api-js" "/var/www/html/static-site/sites/default/files"
