#!/bin/bash

rm -rf /var/www/html/static-site
if [[ "$1" == "--production" ]]; then
  GENERATE_STATIC_SITE=1 drush tome:static --uri=https://frees.au
else
  GENERATE_STATIC_SITE=1 drush tome:static --uri=https://fs-web-static-site.ddev.site
fi