name: fs-web
type: drupal10
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
router_http_port: "8080"
router_https_port: "8443"
xdebug_enabled: false
additional_hostnames:
    - fs-web-static-site
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
disable_settings_management: true
web_environment:
    - DRUSH_OPTIONS_URI=https://fs-web.ddev.site:8443
corepack_enable: false
