name: fs-web
type: drupal10
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames:
  - fs-web-static-site
additional_fqdns: []
database:
    type: mariadb
    version: "10.4"
use_dns_when_possible: true
composer_version: "2"
disable_settings_management: true
web_environment:
    - DRUSH_OPTIONS_URI=https://fs-web.ddev.site
corepack_enable: false
