name: fs-web
type: drupal10
docroot: web
php_version: "8.1"
webserver_type: nginx-fpm

# I am opinionated about settings.php and friends.
disable_settings_management: true
web_environment:
- DRUSH_OPTIONS_URI=https://fs-web.ddev.site
