name: fs-web
type: drupal10
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
disable_settings_management: true # @see web/sites/default/docker.settings.php
web_environment:
- DRUSH_OPTIONS_URI=https://fs-web.ddev.site
