name: Recipe Test
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Composer install
        uses: kohlerdominik/docker-run-action@v1
        with:
          image: composer
          shell: /bin/bash
          workdir: /app
          volumes:
            ${{ github.workspace }}:/app
          run: |
            composer install --ignore-platform-reqs

      - name: Recipe install
        uses: kohlerdominik/docker-run-action@v1
        with:
          image: bitnami/php-fpm:8.2
          shell: /bin/bash
          workdir: /app
          volumes:
            ${{ github.workspace }}:/app
          run: |
            cd web && php -d memory_limit=512M core/scripts/drupal install ../recipes/freesauce/ce
